---
title: "Typing Math in R Markdown: Rudiments of LaTeX"
subtitle: "Department of Mathematics, Soochow University"
author: "Chang-Ye Tu"
date: "`r format(Sys.time(), '%d %B %Y')`" 
output: 
  bookdown::html_document2:
    theme: lumen
    highlight: tango	
    toc: false 
    toc_depth: 3
    number_sections: false 
---

# Typing Math in R Markdown: Rudiments of LaTeX

Source: [Mathematics StackExchange](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference)

## Fundamentals 

- Escape Characters: `& % $ # _ { } ~ ^ \`  
  - Raw character for the first seven: Typeset by prepending a backslash `\`
  - Raw character for the last three: use `\textasciitilde`, `\textasciicircum`, and `\textbackslash` respectively

- For inline formulas, enclose the formula in `$`
  - Get $2\times 3\pm 5=6\pm 5$ by `$2\times 3\pm 5=6\pm 5$`
- For displayed formulas, use `$$`
  - Get $$\int_{-\infty}^\infty e^{-x^2}\,\text{d}x=\sqrt{\pi}$$ by `$$\int_{-\infty}^\infty e^{-x^2}\,\text{d}x=\sqrt{\pi}$$`

- For superscripts and subscripts, use `^` and `_`
  - Get $x_i^2$ by `x_i^2`, $\log_2 x$ by `\log_2 x`

- Groups: superscripts, subscripts, and other operations apply only to the next "group" 
  - A "group" is either a single symbol, or any formula surrounded by curly braces `{ }` 
  - `10^10` becomes $10^10$; should be `10^{10}` 
  - Use curly braces to delimit a formula to which a superscript or subscript applies: `x^5^6` is an error; `{x^y}^z` becomes ${x^y}^z$, `x^{y^z}` becomes $x^{y^z}$ 
  - Observe the differences between `x_i^2`, `x_{i^2}` and `{x_i}^2`: $x_i^2$, $x_{i^2}$, ${x_i}^2$

- Parentheses 
  - Make parentheses and brackets using `()[]`; for curly braces `{}` use `\{` and `\}`
  - These do not scale with the formula in between, so if one write `(\frac{\sqrt x}{y^3})` the parentheses will be too small: $(\frac{\sqrt x}{y^3})$
  - Using `\left(\right)` instead of plain `()` will make the sizes adjust automatically to the formula they enclose: $\left(\frac{\sqrt x}{y^3}\right)$
  - `\left` and `\right` apply to all the following sorts of parentheses: `(` and `)`, `[` and `]`, `\{` and `\}`, `|`, `\vert`, `\Vert`, `\langle` and `\rangle`, `\lceil` and `\rceil`, and `\lfloor` and `\rfloor`  
  - There are also invisible parentheses, denoted by `.` 
    - Get $\left.\frac12\right\rbrace$ by `\left.\frac12\right\rbrace` 
  - If manual size adjustments are required, observe that `\Biggl(\biggl(\Bigl(\bigl((x)\bigr)\Bigr)\biggr)\Biggr)`: $\Biggl(\biggl(\Bigl(\bigl((x)\bigr)\Bigr)\biggr)\Biggr)$

- Sums and integrals: `\sum` and `\int`; the subscript is the lower limit and the superscript is the upper limit
  - Don't forget `{ }` if the limits are more than a single symbol, e.g. $\sum_{i=0}^\infty i^2$ by `\sum_{i=0}^\infty i^2`

- Fractions: `\frac{}{}`, e.g. `\frac{1}{2}`, `\frac{x+y}{2z-5}`, `\frac{\partial^2 u}{\partial x^2}` become $\frac{1}{2}$, $\frac{x+y}{2z-5}$, $\frac{\partial^2 u}{\partial x^2}$.

- Fonts: Use
  - `\mathbb` or `\Bbb` for "blackboard bold": $\mathbb{ABCDEFGHIJKLMNOPQRSTUVWXYZ}$.
  - `\mathbf` for boldface: $\mathbf{ABCDEFGHIJKLMNOPQRSTUVWXYZ\;abcdefghijklmnopqrstuvwxyz}$.
  - `\mathit` for italics: $\mathit{ABCDEFGHIJKLMNOPQRSTUVWXYZ\;abcdefghijklmnopqrstuvwxyz}$.
  - `\pmb` for boldfaced italics: $\pmb{ABCDEFGHIJKLMNOPQRSTUVWXYZ\;abcdefghijklmnopqrstuvwxyz}$.
  - `\mathtt` for "typewriter" font$: \mathtt{ABCDEFGHIJKLMNOPQRSTUVWXYZ\;abcdefghijklmnopqrstuvwxyz}$. 
  - `\mathrm` for roman font: $\mathrm{ABCDEFGHIJKLMNOPQRSTUVWXYZ\;abcdefghijklmnopqrstuvwxyz}$. 
  - `\mathsf` for sans-serif font: $\mathsf{ABCDEFGHIJKLMNOPQRSTUVWXYZ\;abcdefghijklmnopqrstuvwxyz}$.
  - `\mathcal` for "calligraphic" letters: $\mathcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ}$.
  - `\mathscr` for script letters: $\mathscr{ABCDEFGHIJKLMNOPQRSTUVWXYZ}$. 
  - `\mathfrak` for "Fraktur" (old German style) letters: $\mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZ\;abcdefghijklmnopqrstuvwxyz}$.  
- Radical signs / roots: Use `\sqrt`, which adjusts to the size of its argument
  - For complicated expressions, consider using `{...}^{1/2}` instead.

- Special functions such as "lim", "sin", "max", "ln", and so on are normally set in roman font instead of italic font
  - Use `\lim`, `\sin`, etc. to make $\lim$, $\sin$, not $lim$, $sin$ !
  - Use subscripts to attach a notation to `\lim`: e.g. $\lim_{x\to 0}$ by `\lim_{x\to 0}`

- Putting extra literal spaces into formulas will not change the amount of space LaTeX puts in: a␣b and a␣␣␣␣b are both ab
  - To add more space, use `\,` for a thin space, `\;` for a wider space, `\quad` and `\qquad` for larger spaces
  
- To set plain text, use `\text{}`
  - You can nest `$` inside of `\text{}`, for example to access inline formula or spaces.

- Accents and diacritical marks
  - Use `\hat` for a single symbol, `\widehat` for a larger formula
  - There are `\bar`, `\overline`, `\vec`, `\overrightarrow` and `\overleftrightarrow`
  - For dots, use `\dot` and `\ddot`.

- Special characters can be escaped using the `\` character: `\$` for `$`, `\{` for `{`, `\}` for `}`, `\_` for `_`, `\#` for `#`, `\&` for `&`. If you want `\` itself, you should use `\backslash` (symbol) or `\setminus` (binary operation) for `∖`, because `\\` is for a new line.

- Array-Like Environment
  - Using `&` as seperator between row elements
  - Proceed to next row by issuing `\\` 
  - Get $$f(n) = \begin{cases}\frac{n}{2},  & \text{if $n$ is even} \\[2ex] 3n+1, & \text{if $n$ is odd}\end{cases}$$ by
```
$$f(n) = \begin{cases}
  \frac{n}{2}, & \text{if $n$ is even} \\[2ex]
  3n+1,        & \text{if $n$ is odd}
\end{cases}$$
```
  - Get $$\begin{pmatrix}1 & a_1 & a_1^2 & \cdots & a_1^n \\ 1 & a_2 & a_2^2 & \cdots & a_2^n \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 1 & a_m & a_m^2 & \cdots & a_m^n\end{pmatrix}$$ by 
```
$$\begin{pmatrix}
    1      & a_1    & a_1^2  & \cdots & a_1^n  \\ 
    1      & a_2    & a_2^2  & \cdots & a_2^n  \\ 
    \vdots & \vdots & \vdots & \ddots & \vdots \\ 
    1      & a_m    & a_m^2  & \cdots & a_m^n
\end{pmatrix}$$
```

## Selected LaTeX Symbols

| symbol                    | LaTeX                     | symbol                    | LaTeX                     |
|:--------------------------|:--------------------------|:--------------------------|:--------------------------|
|$\alpha$                   | `\alpha`                  | $\beta$                   | `\beta`                   |
|$\Gamma$, $\gamma$         | `\Gamma`, `\gamma`        | $\Delta$, $\delta$        | `\Delta`, `\delta`        |
|$\epsilon$, $\varepsilon$  | `\epsilon`, `\varepsilon` | $\zeta$                   | `\zeta`                   |
|$\eta$                     | `\eta`                    | $\Theta$, $\theta$, $\vartheta$  | `\Theta`, `\theta`, `\vartheta` |
|$\iota$                    | `\iota`                   | $\kappa$                  | `\kappa`                  |
|$\Lambda$, $\lambda$       | `\Lambda`, `\lambda`      | $\mu$                     | `\mu`                     |
|$\nu$                      | `\nu`                     | $\Xi$, $\xi$              | `\Xi`, `\xi`              |
|$\Pi$, $\pi$               | `\Pi`, `\pi`              | $\rho$, $\varrho$         | `\rho`, `\varrho`         |
|$\Sigma$, $\sigma$         | `\Sigma`, `\sigma`        | $\tau$                    | `\tau`                    |
|$\Upsilon$, $\upsilon$     | `\Upsilon`, `\upsilon`    | $\Phi$, $\phi$, $\varphi$ | `\Phi`, `\phi`, `\varphi` |
|$\chi$                     | `\chi`                    | $\Psi$, $\psi$            | `\Psi`, `\psi`            |
|$\Omega$, $\omega$         | `\Omega`, `\omega`        | $\aleph$                  | `\aleph`                  |
|$\lt$                      | `\lt`                     | $\le$                     | `\le`                     |
|$\leq$                     | `\leq`                    | $\leqslant$               | `\leqslant`               |
|$\gt$                      | `\gt`                     | $\ge$                     | `\ge`                     |
|$\geq$                     | `\geq`                    | $\geqslant$               | `\geqslant`               |
|$\neq$                     | `\neq`                    | $\cdot$                   | `\cdot`                   |
|$\times$                   | `\times`                  | $\div$                    | `\div`                    |
|$\pm$                      | `\pm`                     | $\mp$                     | `\mp`                     |
|$\cup$                     | `\cup`                    | $\cap$                    | `\cap`                    |
|$\setminus$                | `\setminus`               | $\subset$                 | `\subset`                 |
|$\subseteq$                | `\subseteq`               | $\subsetneq$              | `\subsetneq`              |
|$\in$                      | `\in`                     | $\notin$                  | `\notin`                  |
|$\emptyset$                | `\emptyset`               | $\varnothing$             | `\varnothing`             |
|${n+1\choose 2k}$ | `{n+1\choose 2k}`,`\binom{n+1}{2k}`| $\ell$                    | `\ell`                    |
|$\to$                      | `\to`                     | $\gets$                   | `\gets`                   |
|$\rightarrow$              | `\rightarrow`             | $\leftarrow$              | `\leftarrow`              |
|$\Rightarrow$              | `\Rightarrow`             | $\Leftarrow$              | `\Leftarrow`              |
|$\mapsto$                  | `\mapsto`                 | $\iff$                    | `\iff`                    |
|$\cup$                     | `\cup`                    | $\cap$                    | `\cap`                    |
|$\land$                    | `\land`,`\wedge`          | $\lor$                    | `\lor`, `\vee`            |
|$\lnot$                    | `\lnot`                   | $\forall$                 | `\forall`                 |
|$\exists$                  | `\exists`                 | $\top$                    | `\top`                    |
|$\bot$                     | `\bot`                    | $\star$                   | `\star`                   |
|$\ast$                     | `\ast`                    | $\oplus$                  | `\oplus`                  |
|$\circ$                    | `\circ`                   | $\bullet$                 | `\bullet`                 |
|$\approx$                  | `\approx`                 | $\sim$                    | `\sim`                    |
|$\simeq$                   | `\simeq`                  | $\cong$                   | `\cong`                   |
|$\equiv$                   | `\equiv`                  | $\prec$                   | `\prec`                   |
|$\partial$                 | `\partial`                | $\nabla$                  | `\nabla`                  |
|$\lhd$                     | `\lhd`                    | $\infty$                  | `\infty`                  |
|$\Im$                      | `\Im`                     | $\Re$                     | `\Re`                     |
|$|x|$                      | `|x|`, `\vert x\vert`     | $\|x\|$                   | `\|x\|`, `\Vert x\Vert`   |
|$\lfloor x\rfloor$         | `\lfloor x\rfloor`        | $\lceil x\rceil$          | `\lceil x\rceil`          |
|$\langle x\rangle$         | `\langle x\rangle`        | $\lvert x\rvert$          | `\lvert x\rvert`          |
|$\{x\mid x^2\in\mathbb{Z}\}$|`\{x\mid x^2\in\mathbb{Z}\}` | $\iint$, $\iiint$      | `\iint`, `\iiint`         |
|$a_1, a_2, \ldots, a_n$    | `a_1, a_2, \ldots, a_n`   | $a_1 + a_2 + \cdots + a_n$| `a_1 + a_2 + \cdots + a_n`|
|$a\equiv b\pmod n$         | `a\equiv b\pmod n`        | $a\bmod 17$               | `a\bmod 17`               |

# Challanges

- Formal Definition of Limit: Given $\varepsilon > 0$, $\exists\,\delta > 0$ such that $|x - a| < \delta$ $\Longrightarrow$ $|f(x) - L| < \varepsilon$.

- A Problem in Calculus: Find $a$, $b$ such that
$$
    f(x) = \begin{cases} a x^3 & \text{ if } x\leqslant 1 \\ x^2 + b & \text{ if } x > 1\end{cases}
$$   
is differentiable on $\mathbb{R}$.

- The HJB equation of Merton's Problem 
$$
  \frac{\delta^2\beta^{\frac{\gamma}{\delta}}}{\gamma}e^{-\frac{\rho}{\delta}t}u_w^{-\frac{\gamma}{\delta}} + u_{t} +\left(\frac{\delta\nu}{\beta} + rw\right)u_w - \delta(\mu-r)\frac{u_w^2}{u_{w w}} = 0;\quad u(T, w)=0. 
$$

- The Solution of Merton's Problem
$$
  u(t, w) = \frac{\delta^{2\delta}\beta^\gamma}{\gamma}e^{-\rho t}\left(\frac{1-e^{\frac{(\rho-\gamma\mu)(t-T)}{\delta}}}{\rho-\gamma\mu}\right)^\delta\left(w+\frac{\delta\nu}{\beta r}\left(1-e^{r(t-T)}\right)\right)^\gamma
$$

- A Lie Algebra Generator
$$
A_1 = \begin{pmatrix} 
  1 & 0 & 0 & 0 \\ 
  0 & 1 & 0 & 0 \\ 
  -\frac{\varepsilon_1(\rho-r\gamma)}{\gamma} & 0 & 1 & 0 \\ 
  -\frac{\varepsilon_1}{\gamma} & 0 & 0 & 1  
\end{pmatrix}
$$
